name: "Register User"
description: "Request to be registered in the system"
title: "Register: [Your Username]"
labels: ["regist-user"]
body:
  - type: markdown
    attributes:
      value: "Welcome! Please check the box below to start your registration with @pkgdbai."
  - type: checkboxes
    id: confirm_start
    attributes:
      label: "Registration Request"
      options:
        - label: "I want to start the registration process"
          required: true
